language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master
        - develop

install: 
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
    - pip install -IM pylama
    - pip install -IM -r requirements.txt

script:
    - make db
    - make audit
    - make test
